# Generated by Django 4.2.2 on 2023-07-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='estreno',
            field=models.BooleanField(default=False, verbose_name='Semana'),
        ),
    ]
