# Generated by Django 4.2.2 on 2023-07-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_remove_film_day_1_remove_film_day_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='film',
            name='day_1',
            field=models.CharField(default=None, max_length=150, verbose_name='Dia 1'),
        ),
        migrations.AddField(
            model_name='film',
            name='day_2',
            field=models.CharField(default=None, max_length=150, verbose_name='Dia 2'),
        ),
        migrations.AddField(
            model_name='film',
            name='day_3',
            field=models.CharField(default=None, max_length=150, verbose_name='Dia 3'),
        ),
    ]
