# Generated by Django 4.2.2 on 2023-07-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_booking_booking_date_film_day_1_film_day_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='film',
            field=models.CharField(default='No title added.', editable=False, max_length=150, verbose_name='Pelicula'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tickets_quantity',
            field=models.IntegerField(),
        ),
    ]
