# Generated by Django 4.2.2 on 2023-07-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_booking_booking_date_alter_booking_film_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='film',
            field=models.CharField(default='No film added.', editable=False, max_length=150, verbose_name='Pelicula'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='schedule',
            field=models.CharField(default='No schedule added.', max_length=150, verbose_name='Agenda'),
        ),
    ]
