# Generated by Django 4.2.2 on 2023-07-11 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_alter_booking_film_alter_booking_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='film',
        ),
    ]
