# Generated by Django 4.2.2 on 2023-07-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_remove_booking_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha Booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tickets_quantity',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
    ]
