# Generated by Django 4.2.2 on 2023-07-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_alter_booking_booking_date_alter_booking_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.CharField(default=None, max_length=150, verbose_name='Fecha Booking'),
        ),
    ]
